/**
 * SAT plan quiz layout — LOCKED.
 *
 * Agents: do not edit this file, funnel.css shell rules, FunnelShell, or
 * QuizStepTemplate structure without owner approval and FUNNEL_LAYOUT_UNLOCK=1.
 *
 * New screens: pick a bodyVariant + swap copy/children only.
 */

export const QUIZ_STEP_BODY_VARIANTS = {
  "tile-grid": "quiz-step--tile-grid",
  "option-list": "quiz-step--option-list",
  copy: "quiz-step--copy"
} as const;

export type QuizStepBodyVariant = keyof typeof QUIZ_STEP_BODY_VARIANTS;

/** Headline scale for `copy` steps — set on QuizStepTemplate, not per-screen CSS. */
export const QUIZ_STEP_HEADLINE_TIERS = {
  hero: "quiz-step-headline-tier--hero",
  compact: "quiz-step-headline-tier--compact"
} as const;

export type QuizStepHeadlineTier = keyof typeof QUIZ_STEP_HEADLINE_TIERS;

export function headlineTierClassFor(
  tier: QuizStepHeadlineTier | undefined
): string | null {
  if (!tier || tier === "hero") {
    return QUIZ_STEP_HEADLINE_TIERS.hero;
  }
  return QUIZ_STEP_HEADLINE_TIERS[tier];
}

/** Files that define layout — guard script blocks agent edits unless unlocked. */
export const FUNNEL_LAYOUT_LOCKED_PATHS = [
  "app/satplan/funnel.css",
  "components/sat-plan/funnel-shell.tsx",
  "components/sat-plan/quiz-step-template.tsx",
  "components/sat-plan/funnel-cta.tsx",
  "lib/sat-plan-funnel/quiz-step-layout.ts"
] as const;

/** Step screens — content only; may import QuizStepTemplate + body components. */
export const FUNNEL_STEP_SCREEN_ALLOWLIST = [
  "components/sat-plan/sat-plan-worries.tsx",
  "components/sat-plan/sat-plan-who.tsx"
] as const;

/** Non-intake funnel components exempt from step-screen rules. */
export const FUNNEL_STEP_SCREEN_EXEMPT = [
  "components/sat-plan/sat-plan-funnel.tsx",
  "components/sat-plan/sat-plan-landing.tsx",
  "components/sat-plan/sat-plan-chapter-stub.tsx"
] as const;

export function bodyClassForVariant(variant: QuizStepBodyVariant): string {
  return QUIZ_STEP_BODY_VARIANTS[variant];
}
