/**
 * Display names for trust score cards — drawn from SSA top ~50 names for
 * births circa 2008–2010 (students ~16–18 in 2026). Mixes common spelling
 * variants (Sophia/Sofia, Zoey/Zoe, etc.). Illustrative only; not live CRM data.
 */

/** One name per trust story card (16 cards). Ethan slot = verified case study. */
export const trustStoryStudentNames: readonly string[] = [
  "Ethan",
  "Sophia",
  "Olivia",
  "Liam",
  "Isabella",
  "Noah",
  "Emily",
  "Lucas",
  "Ava",
  "Jackson",
  "Emma",
  "Aiden",
  "Chloe",
  "Benjamin",
  "Grace",
  "Charlotte"
] as const;

/** Reference pool — top U.S. names at ages 16–18 (SSA 2008–2010 cohort). */
export const trustNamePoolReference = {
  female: [
    "Emma",
    "Olivia",
    "Sophia",
    "Sofia",
    "Isabella",
    "Ava",
    "Emily",
    "Madison",
    "Abigail",
    "Chloe",
    "Mia",
    "Ella",
    "Amelia",
    "Harper",
    "Evelyn",
    "Elizabeth",
    "Charlotte",
    "Grace",
    "Hannah",
    "Lily",
    "Natalie",
    "Zoey",
    "Zoe",
    "Victoria",
    "Brooklyn",
    "Anna",
    "Samantha",
    "Ashley",
    "Riley",
    "Aubrey",
    "Layla",
    "Addison",
    "Audrey",
    "Allison",
    "Sarah",
    "Kaylee",
    "Anna",
    "Hailey",
    "Katherine",
    "Maya"
  ],
  male: [
    "Jacob",
    "Ethan",
    "Michael",
    "Jayden",
    "William",
    "James",
    "Joshua",
    "Noah",
    "Daniel",
    "Alexander",
    "Matthew",
    "Aiden",
    "Anthony",
    "David",
    "Joseph",
    "Jackson",
    "Logan",
    "Andrew",
    "Lucas",
    "Liam",
    "Mason",
    "Benjamin",
    "Elijah",
    "Oliver",
    "Carter",
    "Luke",
    "Gabriel",
    "Owen",
    "Samuel",
    "Ryan",
    "Nathan",
    "Caleb",
    "Dylan",
    "Henry",
    "Sebastian",
    "Jack",
    "Christian",
    "Jonathan",
    "Landon",
    "Isaac"
  ]
} as const;
